language: python
python:
  - '3.8.5'

addons:
  chrome: stable

before_script:
  - pip install -r requirements.txt
  - install-webdrivers --path webdrivers

branches:
  only:
    - master

env: DJANGO_SETTINGS_MODULE='pur_beurre.travis', SECRET_KEY="RadeoncoreI7"

services:
  - postgresql

script:
  - python manage.py test
