language: python
python:
  - '3.8.5'

before_script:
  - pip install -r requirements.txt

branches:
  only:
    - master

env: DJANGO_SETTINGS_MODULE='pur_beurre.travis', SECRET_KEY="8!zly&9&%9nddbbe72-nc@h)&+-@7&i&og5!@!=p=fw1=o*mu3"

services:
  - postgresql

script:
  - python manage.py test
