language: python
python:
  - '3.8.5'

before_script:
  - pip install -r requirements.txt

branches:
  only:
    - master

env: DJANGO_SETTINGS_MODULE='pur_beurre.travis', SECRET_KEY='kzaefjoizrhjfizhrfzerf'

services:
  - postgresql

script:
  - python manage.py test
